import { expect, test } from '@playwright/test';

test('Trash recovers history and permanent deletion requires confirmation', async ({ page }) => {
  await page.route('https://bible-api.com/**', route => route.abort());
  await page.goto('/');
  await page.getByRole('button', { name: 'New blank entry' }).click();
  await page.getByLabel('Title', { exact: true }).fill('Recoverable reflection');
  const body = page.getByRole('textbox', { name: 'Reflection Markdown supported' });
  await body.fill('First draft');
  await expect(page.getByRole('status').filter({ hasText: /^Draft saved$/ })).toBeVisible();
  await body.fill('Finished reflection');
  await page.getByRole('button', { name: 'Finish entry' }).click();
  await page.getByRole('button', { name: 'View revision history' }).click();
  const history = page.getByRole('region', { name: 'Revision history' });
  await expect(history.getByRole('button', { name: /^Version / }).first()).toBeVisible();
  const count = await history.getByRole('button', { name: /^Version / }).count();
  expect(count).toBeGreaterThan(1);
  await history.getByRole('button', { name: 'Delete this version' }).first().click();
  await page.getByRole('button', { name: 'Cancel deletion' }).click();
  await expect(history.getByRole('button', { name: /^Version / })).toHaveCount(count);
  await history.getByRole('button', { name: 'Delete this version' }).first().click();
  await page.getByRole('button', { name: 'Confirm permanent deletion' }).click();
  await expect(history.getByRole('button', { name: /^Version / })).toHaveCount(count - 1);
  await page.getByRole('button', { name: 'Move entry to Trash' }).click();
  const trash = page.getByRole('region', { name: 'Trash', exact: true });
  await expect(trash).toContainText('Recoverable reflection');
  await page.reload();
  await page.getByRole('button', { name: 'View Trash' }).click();
  await trash.getByRole('button', { name: 'Restore entry' }).click();
  await page.getByRole('navigation', { name: 'Journal entries' }).getByRole('button', { name: /Recoverable reflection/ }).click();
  await expect(body).toHaveValue('Finished reflection');
  await page.getByRole('button', { name: 'Move entry to Trash' }).click();
  await trash.getByRole('button', { name: 'Delete entry permanently' }).click();
  await page.getByRole('button', { name: 'Confirm permanent deletion' }).click();
  await expect(trash).toContainText('Trash is empty.');
  await page.reload();
  await page.getByRole('button', { name: 'View Trash' }).click();
  await expect(trash).toContainText('Trash is empty.');
  await expect(page.getByRole('navigation', { name: 'Journal entries' })).not.toContainText('Recoverable reflection');
});
